dist: trusty
sudo: required
language: bash
services:
  - docker
before_install:
  - sudo apt-get install -y expect
install:
  - ./config-expect.sh
  - ./po install
script:
  - po photon build build-test/
  - po electron clean build-test/
  - po electron build build-test/
  - po P1 clean build-test/
  - po P1 build build-test/
  - po core clean build-test/
  - po core build build-test/
  - po pi clean build-test/
  - po pi build build-test/
